### ISSUE TITLE
Error for some special characters when running `doi2pdf`

### ISSUE THREAD

**Issue by kellertuer** [gerw/mathbin#8]
On my machine when running `doi2pdf 10.1137/0803026`

I get 

````
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
Traceback (most recent call last):
  File "/Users/ronnber/Repositories/numapde/numapde-bibliography/mathbin/doi2pdfname.py", line 7, in <module>
    tree = etree.parse(sys.argv[1])
  File "src/lxml/etree.pyx", line 3521, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1859, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1885, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1789, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1177, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "/tmp/368219713", line 32
lxml.etree.XMLSyntaxError: Entity 'nbsp' not defined, line 32, column 60
````

which for me looks like an `&nbsp;` (nonbreaking space in html) is not properly handled/escaped when trying to generate the name?

**Comment by gerw** [comment]
It seems that your `grep` is missing `-P` for perl regexp.

**Comment by kellertuer** [comment]
Hm, that is interesting, because it is the same machine I wrote the tutorial for that is now  in the Readme and I am not aware of having changed grep.

Edit: Maybe it would be better to have these script really a little bit more system independent. The only thing keeping me from starting that is, that the php code is really not that easy to read, i.e. a little hard to understand what it does and how it is actually done. Maybe I‘ll try to reimplement this in one language without so many dependencies at some point.
